### ISSUE TITLE
Migrate to R 4.0

### ISSUE THREAD

**Issue by zkamvar** [zkamvar/carpentries-docker-test#11]
Last month, we officially created a blog post announcing that the Carpentries lessons would be migrating to R 4.0: https://carpentries.org/blog/2020/08/r-4-migration/

This tool should migrate as well, and afact, there are changes to how this container works on the rocker side, so that will need to be taken into account, but I think it should be as simple as changing the version number.

**Comment by stefpiatek** [comment]
I've ended up doing this to work on the r-novice-gapminder lesson, if you'd like a PR?

**Comment by zkamvar** [comment]
If the modified container worked for you, then yes, a PR would be lovely :+1:
