### ISSUE TITLE
Pin ruby version

### ISSUE THREAD

**Issue by zkamvar** [zkamvar/carpentries-docker-test#4]
At the moment, we only support Jekyll 3.8.5, but haven't pinned the ruby version. Ruby updated and now throws warnings for some jekyll patterns (see jekyll/jekyll#7947). Pinning it to 2.6.3 should work

**Comment by fmichonneau** [comment]
We should stick to the [version that GitHub pages uses](https://pages.github.com/versions/) which is 2.5.8.

**Comment by zkamvar** [comment]
Thank you for linking the info!
